CREATE TABLE "CODE_TYPES" (   
      "ID" NUMBER NOT NULL, 
      "TYPE_CODE" VARCHAR2(50 BYTE) NOT NULL, 
      CONSTRAINT "CODE_TYPES_PK" PRIMARY KEY ("ID"), 
      CONSTRAINT "CODE_TYPES_UK1" UNIQUE ("TYPE_CODE")
);
  
CREATE TABLE "CODE_VALUES" (  
      "ID" NUMBER NOT NULL, 
      "CODE" VARCHAR2(50 BYTE) NOT NULL, 
      "DESCRIPTION" VARCHAR2(4000 BYTE) NOT NULL, 
      "ATTRIBUTES" VARCHAR2(4000 BYTE), 
      "TYPE_ID" NUMBER NOT NULL, 
      "EFFECTIVE_FROM" TIMESTAMP (6), 
      "EFFECTIVE_TO" TIMESTAMP (6), 
      CONSTRAINT "CODE_VALUES_PK" PRIMARY KEY ("ID"), 
      CONSTRAINT "CODE_VALUES_UK1" UNIQUE ("TYPE_ID", "CODE"), 
      CONSTRAINT "CODE_VALUES_FK1" FOREIGN KEY ("TYPE_ID") REFERENCES "CODE_TYPES"("ID")
);

CREATE SEQUENCE "CODE_TYPES_SEQ" INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE "CODE_VALUES_SEQ" INCREMENT BY 1 START WITH 1;
/

CREATE OR REPLACE TRIGGER CODE_TYPES_TRG 
BEFORE INSERT ON CODE_TYPES 
FOR EACH ROW 
BEGIN
    IF INSERTING THEN
      SELECT CODE_TYPES_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER CODE_VALUES_TRG 
BEFORE INSERT ON CODE_VALUES 
FOR EACH ROW 
BEGIN
    IF INSERTING THEN
      SELECT CODE_VALUES_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
END;
/